from dataclasses import dataclass
from typing import Protocol


@dataclass(frozen=True)
class AIResult:
    """Represents the result of an AI provider operation.

    Attributes:
        content (str): The content generated by the AI provider.
        provider (str): The name of the AI provider that generated the content.
        model (str): The model used by the AI provider to generate the content.

    """

    content: str
    provider: str
    model: str


class AIProvider(Protocol):
    """Contract for LLM provider adapters (Groq, Gemini).

    The ai gateway in infrastructure/ai selects among registered providers, handles degradation, and calls through this interface
    """

    @property
    def provider_name(self) -> str:
        """Returns the name of the AI provider.

        Returns:
            str: The name of the AI provider.

        """
        ...

    async def complete(
        self, prompt: str, system_prompt: str | None = None, max_tokens: int = 500
    ) -> AIResult:
        """Generate a completion for the given prompt using the AI provider.

        Args:
            prompt (str): The input prompt for the AI model.
            system_prompt (str | None): An optional system prompt to guide the AI model.
            max_tokens (int): The maximum number of tokens to generate in the completion.

        """
        ...
